import './app-bar.js';
import './footer-bar.js';
import './main-section.js';
import './recommended-list.js';
import './restaurant-item.js';
import './testimonial-list.js';
import './testimonial-item.js';
import './food-item.js';
import './drink-item.js';
